name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  backend:
    name: Backend (lint, typecheck, tests, openapi)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        id: py
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup uv
        uses: astral-sh/setup-uv@v2

      - name: Cache backend venv
        uses: actions/cache@v4
        with:
          path: backend/.venv
          key: venv-${{ runner.os }}-py${{ steps.py.outputs.python-version }}-${{ hashFiles('backend/requirements-ci.txt') }}

      - name: Create venv & install deps
        run: |
          cd backend
          uv venv --python=${{ steps.py.outputs.python-version }}
          uv pip install -r requirements-ci.txt

      - name: Ruff (lint)
        run: |
          cd backend
          uv run ruff check .

      - name: Mypy (typecheck)
        run: |
          cd backend
          uv run mypy .

      - name: Pytest (backend)
        run: |
          cd backend
          uv run pytest tests -q

      - name: Generate OpenAPI JSON
        run: |
          cd backend
          uv run python -c "import json; from app.main import create_app; print(json.dumps(create_app().openapi()))" > ../backend_openapi.json

      - name: Upload OpenAPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi
          path: backend_openapi.json

  frontend:
    name: Frontend (types, tests)
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install FE deps
        run: |
          cd frontend
          npm ci

      - name: Download OpenAPI artifact
        uses: actions/download-artifact@v4
        with:
          name: openapi
          path: frontend

      - name: Generate API types
        run: |
          cd frontend
          npx --yes openapi-typescript ./backend_openapi.json -o ./src/shared/types/api.d.ts --export-type

      - name: Vitest (frontend)
        run: |
          cd frontend
          npm run test:run
