name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  backend:
    name: Backend (lint, typecheck, tests, openapi)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup uv
        uses: astral-sh/setup-uv@v2

      - name: Install backend deps (CI)
        run: |
          cd backend
          uv pip install -r requirements-ci.txt

      - name: Ruff (lint)
        run: |
          cd backend
          uv run ruff check .

      - name: Mypy (typecheck)
        run: |
          cd backend
          uv run mypy .

      - name: Pytest (backend)
        run: |
          cd backend
          uv run pytest tests -q

      - name: Generate OpenAPI JSON (artifact)
        run: |
          cd backend
          uv run python -c "import json; from app.main import create_app; print(json.dumps(create_app().openapi()))" > ..\backend_openapi.json

      - name: Upload OpenAPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi
          path: backend_openapi.json

  frontend:
    name: Frontend (types, tests)
    runs-on: windows-latest
    needs: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install FE deps
        run: |
          cd frontend
          npm ci

      - name: Download OpenAPI artifact
        uses: actions/download-artifact@v4
        with:
          name: openapi
          path: frontend

      - name: Generate API types from OpenAPI file
        run: |
          cd frontend
          npx openapi-typescript .\backend_openapi.json -o .\src\shared\types\api.d.ts --export-type

      - name: Vitest (frontend)
        run: |
          cd frontend
          npm run test:run
